import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";

import "./globals.css";

const roboto = Ubuntu({
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <Navbar />
        <main className="w-full h-full translate-y-[42px]">{children}</main>
      </body>
    </html>
  );
}
